// Code generated by "stringer -type=nodeType"; DO NOT EDIT.

package main

import "strconv"

const _nodeType_name = "nodeErrornodeAppnodeLamnodeIdentifiernodeNumbernodeBool"

var _nodeType_index = [...]uint8{0, 9, 16, 23, 37, 47, 55}

func (i nodeType) String() string {
	if i < 0 || i >= nodeType(len(_nodeType_index)-1) {
		return "nodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _nodeType_name[_nodeType_index[i]:_nodeType_index[i+1]]
}
